# Artificial Neural Network

### Importing the libraries

In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.2.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [39]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
X = np.delete(X, 1, axis=1)
y = dataset.iloc[:, -1].values

In [33]:
dataset.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='object')

In [24]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [40]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 1] = le.fit_transform(X[:, 1])

In [41]:
print(X[0])

[619 0 42 2 0.0 1 1 1 101348.88]


### Splitting the dataset into the Training set and Test set

In [61]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Sampling Dataset

In [82]:
from imblearn.over_sampling import RandomOverSampler
ros = RandomOverSampler()
X_train, y_train = ros.fit_sample(X_train,y_train)

### Feature Scaling

In [83]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [85]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [86]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [87]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [88]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [89]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [90]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
398/398 [==============================] - 1s 3ms/step - loss: 0.6290 - accuracy: 0.6540
Epoch 2/100
398/398 [==============================] - 1s 3ms/step - loss: 0.5633 - accuracy: 0.7035
Epoch 3/100
398/398 [==============================] - 1s 3ms/step - loss: 0.5352 - accuracy: 0.7197
Epoch 4/100
398/398 [==============================] - 1s 3ms/step - loss: 0.5135 - accuracy: 0.7382
Epoch 5/100
398/398 [==============================] - 1s 4ms/step - loss: 0.4988 - accuracy: 0.7492
Epoch 6/100
398/398 [==============================] - 2s 4ms/step - loss: 0.4907 - accuracy: 0.7520
Epoch 7/100
398/398 [==============================] - 2s 4ms/step - loss: 0.4866 - accuracy: 0.7537
Epoch 8/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4842 - accuracy: 0.7551
Epoch 9/100
398/398 [==============================] - 1s 3ms/step - loss: 0.4825 - accuracy: 0.7566
Epoch 10/100
398/398 [==============================] - 1s 2ms/step - loss: 0.4813 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Estimated Salary: \$ 50000

**Solution**

In [91]:
print(ann.predict(sc.transform([[ 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

[[ True]]


### Predicting the Test set results

In [94]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

### Making the Confusion Matrix and Calculating the Precision and Recall

In [95]:
from sklearn.metrics import confusion_matrix, precision_recall_fscore_support
cm = confusion_matrix(y_test, y_pred)
print(cm)
print(precision_recall_fscore_support(y_test, y_pred))

[[1275  320]
 [ 108  297]]
(array([0.92190889, 0.48136143]), array([0.79937304, 0.73333333]), array([0.85627938, 0.58121331]), array([1595,  405]))
